### PR TITLE
Bahasa Indonesia Transalation

### PR DESCRIPTION
**Pull request by KrenZfer**
Hi edlyn,

Nice Calendar there, i hope this will add more language variety.

### CODE REVIEW

**Comment by edlynvillegas** [comment]
Hi there! This will be a nice addition to the project. :) But please add also the minified version so I can merge it, thank you!

**Comment by KrenZfer** [comment]
Ohh wait, forgot to include it, my bad,

**Comment by KrenZfer** [comment]
Hi, 
done included minified version of it,

Cheers,

**Review by edlynvillegas — APPROVED** [review]
Nice work! :+1:

**Pull request merged**
